import type { PublicPlayer } from "./app-context"

/**
 * Shared player data used in leaderboard, match rosters, and public profiles.
 * In production this would come from a database.
 */
export const allPlayers: PublicPlayer[] = [
  {
    rank: 1,
    name: "OmegaPrime",
    avatar: "/avatars/avatar-5.jpg",
    robloxId: "110293847",
    elo: 2150,
    wins: 487,
    losses: 113,
    winRate: 81.2,
    headshotAccuracy: 54.3,
    bio: "Main AWPer, looking for a team. #1 Peekit Champion.",
    frame: "gold",
  },
  {
    rank: 2,
    name: "PhantomX",
    avatar: "/avatars/avatar-4.jpg",
    robloxId: "220384756",
    elo: 1980,
    wins: 412,
    losses: 138,
    winRate: 74.9,
    headshotAccuracy: 48.7,
    bio: "Entry fragger. Always first through the door.",
    frame: "silver",
  },
  {
    rank: 3,
    name: "StormBreak",
    avatar: "/avatars/avatar-3.jpg",
    robloxId: "330475819",
    elo: 1870,
    wins: 365,
    losses: 145,
    winRate: 71.6,
    headshotAccuracy: 42.1,
    bio: "IGL / Support. Strategy over aim.",
    frame: "bronze",
  },
  {
    rank: 4,
    name: "Player_1",
    avatar: "/avatar.jpg",
    robloxId: "440567892",
    elo: 1450,
    wins: 218,
    losses: 124,
    winRate: 63.7,
    headshotAccuracy: 45.2,
    bio: "Competitive BloxStrike player. Climbing the ranks.",
    frame: "gold",
  },
  {
    rank: 5,
    name: "xNova",
    avatar: "/avatars/avatar-1.jpg",
    robloxId: "550612345",
    elo: 1380,
    wins: 195,
    losses: 130,
    winRate: 60.0,
    headshotAccuracy: 39.8,
    bio: "Rifler. Consistent aim, never tilts.",
    frame: "neon",
  },
  {
    rank: 6,
    name: "ByteStorm",
    avatar: "/avatars/avatar-2.jpg",
    robloxId: "660723456",
    elo: 1420,
    wins: 210,
    losses: 140,
    winRate: 60.0,
    headshotAccuracy: 41.5,
    bio: "Lurker main. Flanking is an art.",
    frame: "none",
  },
  {
    rank: 7,
    name: "DarkSpectre",
    avatar: "/avatars/avatar-6.jpg",
    robloxId: "770834567",
    elo: 1400,
    wins: 200,
    losses: 150,
    winRate: 57.1,
    headshotAccuracy: 37.9,
    bio: "Anchor player. Holding sites since day one.",
    frame: "bronze",
  },
  {
    rank: 8,
    name: "NeonBlade",
    avatar: "/avatars/avatar-6.jpg",
    robloxId: "880945678",
    elo: 1350,
    wins: 180,
    losses: 160,
    winRate: 52.9,
    headshotAccuracy: 35.6,
    bio: "Aggressive support. Utility expert.",
    frame: "none",
  },
  {
    rank: 9,
    name: "VortexKing",
    avatar: "/avatars/avatar-1.jpg",
    robloxId: "991056789",
    elo: 1390,
    wins: 190,
    losses: 160,
    winRate: 54.3,
    headshotAccuracy: 38.2,
    bio: "Flex player. Can play any role on the team.",
    frame: "silver",
  },
  {
    rank: 10,
    name: "ZeroGrav",
    avatar: "/avatars/avatar-3.jpg",
    robloxId: "102167890",
    elo: 1310,
    wins: 170,
    losses: 175,
    winRate: 49.3,
    headshotAccuracy: 33.1,
    bio: "Learning and improving every day.",
    frame: "none",
  },
  {
    rank: 11,
    name: "BlazeFury",
    avatar: "/avatars/avatar-5.jpg",
    robloxId: "113278901",
    elo: 1360,
    wins: 185,
    losses: 165,
    winRate: 52.9,
    headshotAccuracy: 36.4,
    bio: "Rush B specialist. No fear.",
    frame: "none",
  },
  {
    rank: 12,
    name: "IronClad",
    avatar: "/avatars/avatar-2.jpg",
    robloxId: "124389012",
    elo: 1300,
    wins: 160,
    losses: 180,
    winRate: 47.1,
    headshotAccuracy: 31.8,
    bio: "Grinding the ladder one game at a time.",
    frame: "none",
  },
  {
    rank: 13,
    name: "CrashCode",
    avatar: "/avatars/avatar-4.jpg",
    robloxId: "135490123",
    elo: 1340,
    wins: 175,
    losses: 175,
    winRate: 50.0,
    headshotAccuracy: 34.2,
    bio: "Clutch or kick. That is the way.",
    frame: "none",
  },
  {
    rank: 14,
    name: "SkyRaider",
    avatar: "/avatars/avatar-1.jpg",
    robloxId: "146501234",
    elo: 1280,
    wins: 150,
    losses: 190,
    winRate: 44.1,
    headshotAccuracy: 29.7,
    bio: "New to competitive. Improving fast.",
    frame: "none",
  },
  {
    rank: 15,
    name: "GhostRunner",
    avatar: "/avatars/avatar-6.jpg",
    robloxId: "157612345",
    elo: 1260,
    wins: 140,
    losses: 200,
    winRate: 41.2,
    headshotAccuracy: 28.3,
    bio: "Silent but deadly. Eco round king.",
    frame: "none",
  },
]

/** Look up a player by name. Returns undefined if not found. */
export function findPlayer(name: string): PublicPlayer | undefined {
  return allPlayers.find(
    (p) => p.name.toLowerCase() === name.toLowerCase()
  )
}
